name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Oder dein Standardbranch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/mein-image:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/mein-image:latest
